### ISSUE TITLE
fatal error: 'string' file not found

### ISSUE THREAD

**Issue by mxmlnkn** [DigiDNA/ISOBMFF#12]
I'm on Linux.

When running `make` in the top-level, I get:

```
[ ISOBMFF ]> Compiling C++ file [ Release - x86_64 ]: HVCC.cpp
In file included from ISOBMFF/source/HVCC.cpp:31:
In file included from ISOBMFF/include/ISOBMFF/HVCC.hpp:36:
In file included from ISOBMFF/include/ISOBMFF/FullBox.hpp:36:
In file included from ISOBMFF/include/ISOBMFF/Box.hpp:36:
ISOBMFF/include/ISOBMFF/BinaryStream.hpp:34:10: fatal error: 'string' file not found
#include <string>
         ^
1 error generated.
make[1]: *** [Submodules/makelib/Targets.mk:220: Build/Release/Intermediates/x86_64/HVCC.cpp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
[ ISOBMFF ]> Compiling C++ file [ Release - x86_64 ]: STSD.cpp
In file included from ISOBMFF/source/STSD.cpp:31:
In file included from ISOBMFF/include/ISOBMFF/STSD.hpp:36:
In file included from ISOBMFF/include/ISOBMFF/FullBox.hpp:36:
In file included from ISOBMFF/include/ISOBMFF/Box.hpp:36:
ISOBMFF/include/ISOBMFF/BinaryStream.hpp:34:10: fatal error: 'string' file not found
#include <string>
         ^
```

It looks like it is compiling C instead of C++? With `make SHELL='sh -x'`, I see:

```
+ echo -e [\x1b[32;01m ISOBMFF \x1b[0m]> Compiling C++ file [ \x1b[36;01mRelease - x86_64\x1b[0m ]: \x1b[33;01m\x1b[30;01mILOC-Item-Extent.cpp\x1b[0m\x1b[0m
-e [\x1b[32;01m ISOBMFF \x1b[0m]> Compiling C++ file [ \x1b[36;01mRelease - x86_64\x1b[0m ]: \x1b[33;01m\x1b[30;01mILOC-Item-Extent.cpp\x1b[0m\x1b[0m
+ clang -Werror -Wall -fPIC -Os -stdlib=libc++ -fno-strict-aliasing -ISubmodules/PIMPL/PIMPL/include -IISOBMFF/include/ -std=c++11 -o Build/Release/Intermediates/x86_64/ILOC-Item-Extent.cpp.o -c ISOBMFF/source/ILOC-Item-Extent.cpp
In file included from ISOBMFF/source/ILOC-Item-Extent.cpp:31:
In file included from ISOBMFF/include/ISOBMFF/ILOC.hpp:36:
In file included from ISOBMFF/include/ISOBMFF/FullBox.hpp:36:
In file included from ISOBMFF/include/ISOBMFF/Box.hpp:36:
ISOBMFF/include/ISOBMFF/BinaryStream.hpp:34:10: fatal error: 'string' file not found
#include <string>
         ^
1 error generated.
make[1]: *** [Submodules/makelib/Targets.mk:220: Build/Release/Intermediates/x86_64/ILOC-Item-Extent.cpp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

It looks like it is using clang instead of clang++ for some reason, but `CC=clang++ make`, `make CC=clang++` or changing clang to clang++ in the Makefile don't seem to work either.

Compiling a minimal example with `clang test.cpp -std=c++11 && ./a.out` works however, so it must be a build system issue.

```c++
#include <iostream>
#include <string>

int main()
{
    std::cout << std::string( 5, 'A' ) << std::endl;
    return 0;
}
```

**Comment by macmade** [comment]
Which Linux distribution are you using?

**Comment by macmade** [comment]
You probably don't have `libc++` installed. Try your example with `-stdlib=libc++`.

**Comment by mxmlnkn** [comment]
`-std=libc++` does indeed lead to the same problem for the example.

**Comment by mxmlnkn** [comment]
I'm using Debian.

I had libc++ installed:
```
ii  libc++1:amd64                        3.7.0-1                 amd64                   LLVM C++ Standard library
```

Would have surprised me if not. I tried to install `libc++-dev` but it didn't help and now I have these package versions (I hope my system doesn't break...)
```
+++-====================================-=======================-=======================-==============================================================================
ii  libc++-7-dev:amd64                   1:7.0.1-8               amd64                   LLVM C++ Standard library (development files)
ii  libc++-dev:amd64                     1:7.0-47.1              amd64                   LLVM C++ Standard library (development files)
un  libc++-x.y                           <none>                  <none>                  (no description available)
un  libc++-x.y-dev                       <none>                  <none>                  (no description available)
ii  libc++1:amd64                        1:7.0-47.1              amd64                   LLVM C++ Standard library
ii  libc++1-7:amd64                      1:7.0.1-8               amd64                   LLVM C++ Standard library
un  libc++abi-x.y                        <none>                  <none>                  (no description available)
un  libc++abi1                           <none>                  <none>                  (no description available)
ii  libc++abi1-7:amd64                   1:7.0.1-8               amd64                   LLVM low level support for a standard C++ library
```

**Comment by macmade** [comment]
This is a known package issue on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855222

You may try to change the Makefile to use libstdc++ and GCC instead, but I haven’t tried it.

**Comment by mxmlnkn** [comment]
Ok, changing the `-stdlib=libc++` part in `FLAGS_OTHER` to `-stdlib=libstdc++` make the .cpp compile, but then linking fails with:
```
/usr/bin/ld: cannot find -lc++abi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

After removing `-lc++` from `LIBS :=` in the Makefile, it links correctly.

Unfortunately, it only builds the static and shared libraries and not the `ISOBMFF-Dump` command line tool?
I got that to work somehow by manually compiling it:
```
clang -fno-strict-aliasing -ISubmodules/PIMPL/PIMPL/include -IISOBMFF/include/ \
-std=c++o isobmff-dump ISOBMFF-Dump/main.cpp \
Build/Release/Products/x86_64/libISOBMFF.a -lstdc++ -lm
```
and running it with `./isobmff-dump IMG_1234.heic` works.

Btw, the dump prints in one line `- Handler name: [NUL-ASCII-CHAR]`. I don't think printing non-printable ascii characters is intended? It's basically the only non-printable char in the whole output.

**Comment by macmade** [comment]
I’m currently on holiday. I’ll take a closer look when I’m back.

**Comment by ggnull35** [comment]
> Ok, changing the `-stdlib=libc++` part in `FLAGS_OTHER` to `-stdlib=libstdc++` makes the .cpp compile, but then linking fails with:
> 
> ```
> /usr/bin/ld: cannot find -lc++abi
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> After removing `-lc++` from `LIBS :=` in the Makefile, it links correctly.
> 
> Unfortunately, it only builds the static and shared libraries and not the `ISOBMFF-Dump` command line tool?
> I got that to work somehow by manually compiling it:
> 
> ```
> clang -fno-strict-aliasing -ISubmodules/PIMPL/PIMPL/include -IISOBMFF/include/ \
> -std=c++o isobmff-dump ISOBMFF-Dump/main.cpp \
> Build/Release/Products/x86_64/libISOBMFF.a -lstdc++ -lm
> ```
> 
> and running it with `./isobmff-dump IMG_1234.heic` works.
> 
> Btw, the dump prints in one line `- Handler name: [NUL-ASCII-CHAR]`. I don't think printing non-printable ascii characters is intended? It's basically the only non-printable char in the whole output.

Also close the line #LIBS                := -lc++
if linker gives error.

**Comment by zhjb7** [comment]
Maybe you should use g++ instead of clang.
update Makefile like this:
CC                  := g++
FLAGS_CPP           :=
LIBS                :=
