### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by MichaelDenczek** [DigiDNA/ISOBMFF#15]
The documents reference ISOBMFF::TRAK which does not exist in the library.  Additionally, shared pointers are not used correctly:

std::shared_ptr< ISOBMFF::File > file = parser.GetFile();
std::shared_ptr< ISOBMFF::FTYP > ftyp = file.GetTypedBox< ISOBMFF::FTYP >( "ftyp" );

Should be:

std::shared_ptr< ISOBMFF::File > file = parser.GetFile();
std::shared_ptr< ISOBMFF::FTYP > ftyp = file->GetTypedBox< ISOBMFF::FTYP >( "ftyp" );

**Comment by macmade** [comment]
Thanks, this has been fixed in 7a8f51bfe7ef4ee380951e631bde603f62582345. : )
