### ISSUE TITLE
Cannot use mingw32-make on this project

### ISSUE THREAD

**Issue by Alsira** [DigiDNA/ISOBMFF#18]
I can't use mingw32-make on this project. I did download the submodules, but I get this in the terminal:
` 
process_begin: CreateProcess(NULL, uname, ...) failed.
make:
process_begin: CreateProcess(NULL, uname -m, ...) failed.
make:
'cut' is not recognized as an internal or external command,
operable program or batch file.
'[' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
-f was unexpected at this time.
The system cannot find the path specified.
-f was unexpected at this time.
process_begin: CreateProcess(NULL, uname, ...) failed.
make[1]:
process_begin: CreateProcess(NULL, uname -m, ...) failed.
make[1]:
'cut' is not recognized as an internal or external command,
operable program or batch file.
'[' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
-f was unexpected at this time.
The system cannot find the path specified.
-f was unexpected at this time.
process_begin: CreateProcess(NULL, uname, ...) failed.
make[1]:
process_begin: CreateProcess(NULL, uname -m, ...) failed.
make[1]:
'cut' is not recognized as an internal or external command,
operable program or batch file.
'[' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
-f was unexpected at this time.
The system cannot find the path specified.
-f was unexpected at this time.
`
If someone could help me compile this project that would be awesome 😁

**Comment by macmade** [comment]
The supplied Makefile is intended for Linux.  
Since you’re on Windows you should use the supplied VisualStudio solution to build the library.

**Comment by i3i3** [comment]
> I can't use mingw32-make on this project. I did download the submodules, but I get this in the terminal:
> 
> ` 
> 
> process_begin: CreateProcess(NULL, uname, ...) failed.
> 
> make:
> 
> process_begin: CreateProcess(NULL, uname -m, ...) failed.
> 
> make:
> 
> 'cut' is not recognized as an internal or external command,
> 
> operable program or batch file.
> 
> '[' is not recognized as an internal or external command,
> 
> operable program or batch file.
> 
> The system cannot find the path specified.
> 
> -f was unexpected at this time.
> 
> The system cannot find the path specified.
> 
> -f was unexpected at this time.
> 
> process_begin: CreateProcess(NULL, uname, ...) failed.
> 
> make[1]:
> 
> process_begin: CreateProcess(NULL, uname -m, ...) failed.
> 
> make[1]:
> 
> 'cut' is not recognized as an internal or external command,
> 
> operable program or batch file.
> 
> '[' is not recognized as an internal or external command,
> 
> operable program or batch file.
> 
> The system cannot find the path specified.
> 
> -f was unexpected at this time.
> 
> The system cannot find the path specified.
> 
> -f was unexpected at this time.
> 
> process_begin: CreateProcess(NULL, uname, ...) failed.
> 
> make[1]:
> 
> process_begin: CreateProcess(NULL, uname -m, ...) failed.
> 
> make[1]:
> 
> 'cut' is not recognized as an internal or external command,
> 
> operable program or batch file.
> 
> '[' is not recognized as an internal or external command,
> 
> operable program or batch file.
> 
> The system cannot find the path specified.
> 
> -f was unexpected at this time.
> 
> The system cannot find the path specified.
> 
> -f was unexpected at this time.
> 
> `
> 
> If someone could help me compile this project that would be awesome 😁
