### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by vicodark** [DigiDNA/ISOBMFF#2]
I've just tried to run make (on OS X 10.11.6) from the project tld and immediately get the following error:

Makefile:31: Submodules/makelib/Common.mk: No such file or directory
Makefile:81: Submodules/makelib/Targets.mk: No such file or directory
make: *** No rule to make target `Submodules/makelib/Targets.mk'.  Stop.

 The "Submodules/makelib/" directory is indeed empty from a fresh git clone. Am I missing something?

**Comment by macmade** [comment]
Yes, if you don't clone recursively, you need to initialise the submodules:

    git submodule init
    git submodule update

Also, if you're on macOS, there's a Xcode project.

**Comment by vicodark** [comment]
That worked, thanks.
