### ISSUE TITLE
Partial parsing?

### ISSUE THREAD

**Issue by onthegit** [DigiDNA/ISOBMFF#20]
Hello, thanks for the library.
Is partial parsing possible with this library? E.g download say 4-5 mb of large of file and attempt to parse moov from the data or download the last 4-5 mb of the file and attempt to parse the moov if moov is at end?
Thanks.

**Comment by macmade** [comment]
Unfortunately this is not possible at the moment.  
I doubt it will ever be, as the ISO format is not really designed to be streamable this way.

**Comment by onthegit** [comment]
gpac/mp4box.js can parse incrementally..
