### ISSUE TITLE
undefined reference 

### ISSUE THREAD

**Issue by dineshkannaa** [DigiDNA/ISOBMFF#4]
I have cloned recursively , but when i try to use parser , this exception occurs 

undefined reference to `ISOBMFF::Parser::Parse(std::string const&)'
makefile:45: recipe for target 'HEICParser' failed
collect2: error: ld returned 1 exit status

i have linked the library using the command 
g++ -L/home/path/ISOBMFF/Build/Release/Products/x86_64 -o "HEICParser"  ./src/HEICParser.o   -lISOBMFF

I have attached my code
[mycode.txt](https://github.com/DigiDNA/ISOBMFF/files/1970994/mycode.txt)

I have attached my code makefile command
[makefile.txt](https://github.com/DigiDNA/ISOBMFF/files/1971010/makefile.txt)

I have gone through many solutions but nothing helps .. kindly help me to solve this issue

**Comment by macmade** [comment]
The ISOBMFF library is built by default with Clang, using `libc++`.

Although you should be fine using G++ as compiler for your project, you cannot mix two different C++ standard libraries (G++ uses `libstdc++`).

I think this is why your are getting the undefined reference.  
`libc++` renames some symbols on purpose to break compatibility with `libstdc++`, so you don't mix by accident.

Try adding the `-stdlib=libc++` flag to your makefile.

**Comment by dineshkannaa** [comment]
Thank you . As -stdlib=libc++ is not a g++ flag , it fails to compile . but it works with clang++ . I want to convert HEIC to JPEG using this parser , could you suggest me the flow , right now I'm done with getting the "ftyp" box .

**Comment by macmade** [comment]
Can’t help you with that.
