### ISSUE TITLE
Possible issue with Read[Big|Little]EndianFixedPoint methods - fractional part always zero?

### ISSUE THREAD

**Issue by JPeMu** [DigiDNA/ISOBMFF#6]
Looks like this line (in BinaryStream.cpp) cannot work:
fractional     = ( n & fractionalMask ) / ( 1 << fractionalLength );

because fractional is an unsigned int and should be returning a fractional value. Changing fractional to a float and therefore the line to:

fractional     = static_cast< float >( n & fractionalMask ) / ( 1 << fractionalLength );

Should produce the correct result

**Comment by macmade** [comment]
Sorry for being so late, and thanks for the report.
We'll fix that asap.
