### ISSUE TITLE
ISOBMFF-Dump missed atoms

### ISSUE THREAD

**Issue by grylem** [DigiDNA/ISOBMFF#8]
ISOBMFF-Dump  misses many atoms like uuid, pasp etc. ISOBMFF-Explorer does not show either.
Also ISOBMFF-Dump (Explorer) cannot parse *.mov without ftyp.
Is it possible to make it so that ISOBMFF displays all atoms in atoms tree?

**Comment by macmade** [comment]
Files without a `ftyp` box are not valid, as this box is mandatory in ISO/IEC 14496-12.

Not all box types are implemented yet, as the specification is quite heavy.  
In such a case, only the binary data is shown.

There's no ETA for supporting other boxes.  
Pull requests are welcome.
