### ISSUE TITLE
Missing makefiles

### ISSUE THREAD

**Issue by nickniel** [DigiDNA/ISOBMFF#9]
Hello,

I think there are .mk files that are not checked in - I was trying to run a "make" and received this error:

COSML-1686660:ISOBMFF nniels053$ make
Makefile:31: Submodules/makelib/Common.mk: No such file or directory
Makefile:81: Submodules/makelib/Targets.mk: No such file or directory
make: *** No rule to make target `Submodules/makelib/Targets.mk'.  Stop.

Thanks,
-Nick

**Comment by macmade** [comment]
You need to check out submodules as well.

    git submodule update --init --recursive

**Comment by nickniel** [comment]
Ahh, ok. I haven't run across that paradigm before. I might suggest putting a line in the readme file, as that wasn't intuitive to me after just cloning the ISOBMFF repo.

**Comment by mxmlnkn** [comment]
I suggest the same as I had the same problem.
